AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/**/*

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false
