AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/**/*
    - config/**/*
    - vendor/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/support/shared_context.rb

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false
